name: my first github action
on: [push]
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
        - run: echo "Hello world"
        - run: echo "Bye World!"
    print-caio-world:
        runs-on: ubuntu-latest
        steps:
        - run: echo "Hello caio world"
        - run: echo "HEHEHE"
    build-app:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18.12.1'
        - name: install node_modules
          run: npm  i
        - name: build the project
          run: npm run build
        - name: Setup Finished
          run: echo "HURRAY"